;!knitout-2
;;Machine: SWGN2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
inhook 2
x-stitch-number 101
tuck - f20 2
tuck - f18 2
tuck - f16 2
tuck - f14 2
tuck - f12 2
tuck - f10 2
tuck - f8 2
tuck - f6 2
tuck - f4 2
tuck - f2 2
tuck + f1 2
tuck + f3 2
tuck + f5 2
tuck + f7 2
tuck + f9 2
tuck + f11 2
tuck + f13 2
tuck + f15 2
tuck + f17 2
tuck + f19 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
releasehook 2
x-stitch-number 106
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
x-stitch-number 101
rack 0.25
tuck + f21 2
tuck + b21 2
tuck + f22 2
tuck + b22 2
tuck + f23 2
tuck + b23 2
tuck + f24 2
tuck + b24 2
rack 0
x-stitch-number 105
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit + b21 2
knit + b22 2
knit + b23 2
knit + b24 2
xfer f21 bs21
xfer f22 bs22
xfer f23 bs23
xfer f24 bs24
rack -1
xfer bs21 f20
xfer bs22 f21
xfer bs23 f22
xfer bs24 f23
rack 0
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
xfer b21 fs21
xfer b22 fs22
xfer b23 fs23
xfer b24 fs24
rack 1
xfer fs21 b20
xfer fs22 b21
xfer fs23 b22
xfer fs24 b23
rack 0
knit + b20 2
knit + b21 2
knit + b22 2
knit + b23 2
xfer f20 bs20
xfer f21 bs21
xfer f22 bs22
xfer f23 bs23
rack -1
xfer bs20 f19
xfer bs21 f20
xfer bs22 f21
xfer bs23 f22
rack 0
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
xfer b20 fs20
xfer b21 fs21
xfer b22 fs22
xfer b23 fs23
rack 1
xfer fs20 b19
xfer fs21 b20
xfer fs22 b21
xfer fs23 b22
rack 0
knit + b19 2
knit + b20 2
knit + b21 2
knit + b22 2
xfer f19 bs19
xfer f20 bs20
xfer f21 bs21
xfer f22 bs22
rack -1
xfer bs19 f18
xfer bs20 f19
xfer bs21 f20
xfer bs22 f21
rack 0
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
xfer b19 fs19
xfer b20 fs20
xfer b21 fs21
xfer b22 fs22
rack 1
xfer fs19 b18
xfer fs20 b19
xfer fs21 b20
xfer fs22 b21
rack 0
knit + b18 2
knit + b19 2
knit + b20 2
knit + b21 2
xfer f18 bs18
xfer f19 bs19
xfer f20 bs20
xfer f21 bs21
rack -1
xfer bs18 f17
xfer bs19 f18
xfer bs20 f19
xfer bs21 f20
rack 0
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
xfer b18 fs18
xfer b19 fs19
xfer b20 fs20
xfer b21 fs21
rack 1
xfer fs18 b17
xfer fs19 b18
xfer fs20 b19
xfer fs21 b20
rack 0
knit + b17 2
knit + b18 2
knit + b19 2
knit + b20 2
xfer f17 bs17
xfer f18 bs18
xfer f19 bs19
xfer f20 bs20
rack -1
xfer bs17 f16
xfer bs18 f17
xfer bs19 f18
xfer bs20 f19
rack 0
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
xfer b17 fs17
xfer b18 fs18
xfer b19 fs19
xfer b20 fs20
rack 1
xfer fs17 b16
xfer fs18 b17
xfer fs19 b18
xfer fs20 b19
rack 0
knit + b16 2
knit + b17 2
knit + b18 2
knit + b19 2
xfer f16 bs16
xfer f17 bs17
xfer f18 bs18
xfer f19 bs19
rack -1
xfer bs16 f15
xfer bs17 f16
xfer bs18 f17
xfer bs19 f18
rack 0
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
xfer b16 fs16
xfer b17 fs17
xfer b18 fs18
xfer b19 fs19
rack 1
xfer fs16 b15
xfer fs17 b16
xfer fs18 b17
xfer fs19 b18
rack 0
knit + b15 2
knit + b16 2
knit + b17 2
knit + b18 2
xfer f15 bs15
xfer f16 bs16
xfer f17 bs17
xfer f18 bs18
rack -1
xfer bs15 f14
xfer bs16 f15
xfer bs17 f16
xfer bs18 f17
rack 0
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
xfer b15 fs15
xfer b16 fs16
xfer b17 fs17
xfer b18 fs18
rack 1
xfer fs15 b14
xfer fs16 b15
xfer fs17 b16
xfer fs18 b17
rack 0
knit + b14 2
knit + b15 2
knit + b16 2
knit + b17 2
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
xfer f17 bs17
rack -1
xfer bs14 f13
xfer bs15 f14
xfer bs16 f15
xfer bs17 f16
rack 0
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
xfer b14 fs14
xfer b15 fs15
xfer b16 fs16
xfer b17 fs17
rack 1
xfer fs14 b13
xfer fs15 b14
xfer fs16 b15
xfer fs17 b16
rack 0
knit + b13 2
knit + b14 2
knit + b15 2
knit + b16 2
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
rack -1
xfer bs13 f12
xfer bs14 f13
xfer bs15 f14
xfer bs16 f15
rack 0
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
xfer b13 fs13
xfer b14 fs14
xfer b15 fs15
xfer b16 fs16
rack 1
xfer fs13 b12
xfer fs14 b13
xfer fs15 b14
xfer fs16 b15
rack 0
knit + b12 2
knit + b13 2
knit + b14 2
knit + b15 2
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
rack -1
xfer bs12 f11
xfer bs13 f12
xfer bs14 f13
xfer bs15 f14
rack 0
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
xfer b12 fs12
xfer b13 fs13
xfer b14 fs14
xfer b15 fs15
rack 1
xfer fs12 b11
xfer fs13 b12
xfer fs14 b13
xfer fs15 b14
rack 0
knit + b11 2
knit + b12 2
knit + b13 2
knit + b14 2
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
rack -1
xfer bs11 f10
xfer bs12 f11
xfer bs13 f12
xfer bs14 f13
rack 0
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
xfer b11 fs11
xfer b12 fs12
xfer b13 fs13
xfer b14 fs14
rack 1
xfer fs11 b10
xfer fs12 b11
xfer fs13 b12
xfer fs14 b13
rack 0
knit + b10 2
knit + b11 2
knit + b12 2
knit + b13 2
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
rack -1
xfer bs10 f9
xfer bs11 f10
xfer bs12 f11
xfer bs13 f12
rack 0
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
xfer b10 fs10
xfer b11 fs11
xfer b12 fs12
xfer b13 fs13
rack 1
xfer fs10 b9
xfer fs11 b10
xfer fs12 b11
xfer fs13 b12
rack 0
knit + b9 2
knit + b10 2
knit + b11 2
knit + b12 2
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
rack -1
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
xfer bs12 f11
rack 0
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
xfer b9 fs9
xfer b10 fs10
xfer b11 fs11
xfer b12 fs12
rack 1
xfer fs9 b8
xfer fs10 b9
xfer fs11 b10
xfer fs12 b11
rack 0
knit + b8 2
knit + b9 2
knit + b10 2
knit + b11 2
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
rack -1
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
rack 0
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
xfer b8 fs8
xfer b9 fs9
xfer b10 fs10
xfer b11 fs11
rack 1
xfer fs8 b7
xfer fs9 b8
xfer fs10 b9
xfer fs11 b10
rack 0
knit + b7 2
knit + b8 2
knit + b9 2
knit + b10 2
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
rack -1
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
rack 0
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
xfer b7 fs7
xfer b8 fs8
xfer b9 fs9
xfer b10 fs10
rack 1
xfer fs7 b6
xfer fs8 b7
xfer fs9 b8
xfer fs10 b9
rack 0
knit + b6 2
knit + b7 2
knit + b8 2
knit + b9 2
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
rack -1
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
rack 0
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
xfer b6 fs6
xfer b7 fs7
xfer b8 fs8
xfer b9 fs9
rack 1
xfer fs6 b5
xfer fs7 b6
xfer fs8 b7
xfer fs9 b8
rack 0
knit + b5 2
knit + b6 2
knit + b7 2
knit + b8 2
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
rack -1
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
rack 0
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
xfer b5 fs5
xfer b6 fs6
xfer b7 fs7
xfer b8 fs8
rack 1
xfer fs5 b4
xfer fs6 b5
xfer fs7 b6
xfer fs8 b7
rack 0
knit + b4 2
knit + b5 2
knit + b6 2
knit + b7 2
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
rack -1
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
rack 0
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
xfer b4 fs4
xfer b5 fs5
xfer b6 fs6
xfer b7 fs7
rack 1
xfer fs4 b3
xfer fs5 b4
xfer fs6 b5
xfer fs7 b6
rack 0
knit + b3 2
knit + b4 2
knit + b5 2
knit + b6 2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
rack -1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
rack 0
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
xfer b3 fs3
xfer b4 fs4
xfer b5 fs5
xfer b6 fs6
rack 1
xfer fs3 b2
xfer fs4 b3
xfer fs5 b4
xfer fs6 b5
rack 0
knit + b2 2
knit + b3 2
knit + b4 2
knit + b5 2
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
rack -1
xfer bs2 f1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
rack 0
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b2 fs2
xfer b3 fs3
xfer b4 fs4
xfer b5 fs5
rack 1
xfer fs2 b1
xfer fs3 b2
xfer fs4 b3
xfer fs5 b4
rack 0
knit + b1 2
knit + b2 2
knit + b3 2
knit + b4 2
xfer b4 f4
knit - f4 2
rack +1
xfer f4 b3
knit + b3 2
rack 0
xfer b3 f3
knit - f3 2
rack +1
xfer f3 b2
knit + b2 2
rack 0
xfer b2 f2
knit - f2 2
rack +1
xfer f2 b1
knit + b1 2
rack 0
xfer b1 f1
knit - f1 2
knit + f1 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
outhook 2
drop f20
drop f19
drop f18
drop f17
drop f16
drop f15
drop f14
drop f13
drop f12
drop f11
drop f10
drop f9
drop f8
drop f7
drop f6
drop f5
drop f4
drop f3
drop f2
drop f1
