;!knitout-2
;;Machine: SWGN2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
inhook 3
x-stitch-number 101
rack -0.75
tuck - f20 3
tuck - b20 3
tuck - f19 3
tuck - b19 3
tuck - f18 3
tuck - b18 3
tuck - f17 3
tuck - b17 3
tuck - f16 3
tuck - b16 3
rack 0
x-stitch-number 105
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
releasehook 3
knit - b20 3
knit - b19 3
knit - b18 3
knit - b17 3
knit - b16 3
miss - b15 3
xfer f16 bs16
xfer f17 bs17
xfer f18 bs18
xfer f19 bs19
xfer f20 bs20
rack -1
xfer bs16 f15
xfer bs17 f16
xfer bs18 f17
xfer bs19 f18
xfer bs20 f19
rack 0
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
tuck + f20 3
xfer b16 fs16
xfer b17 fs17
xfer b18 fs18
xfer b19 fs19
xfer b20 fs20
rack 1
xfer fs16 b15
xfer fs17 b16
xfer fs18 b17
xfer fs19 b18
xfer fs20 b19
rack 0
knit - b19 3
knit - b18 3
knit - b17 3
knit - b16 3
knit - b15 3
miss - b14 3
xfer f15 bs15
xfer f16 bs16
xfer f17 bs17
xfer f18 bs18
xfer f19 bs19
rack -1
xfer bs15 f14
xfer bs16 f15
xfer bs17 f16
xfer bs18 f17
xfer bs19 f18
rack 0
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
tuck + f19 3
xfer b15 fs15
xfer b16 fs16
xfer b17 fs17
xfer b18 fs18
xfer b19 fs19
rack 1
xfer fs15 b14
xfer fs16 b15
xfer fs17 b16
xfer fs18 b17
xfer fs19 b18
rack 0
knit - b18 3
knit - b17 3
knit - b16 3
knit - b15 3
knit - b14 3
miss - b13 3
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
xfer f17 bs17
xfer f18 bs18
rack -1
xfer bs14 f13
xfer bs15 f14
xfer bs16 f15
xfer bs17 f16
xfer bs18 f17
rack 0
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
tuck + f18 3
xfer b14 fs14
xfer b15 fs15
xfer b16 fs16
xfer b17 fs17
xfer b18 fs18
rack 1
xfer fs14 b13
xfer fs15 b14
xfer fs16 b15
xfer fs17 b16
xfer fs18 b17
rack 0
knit - b17 3
knit - b16 3
knit - b15 3
knit - b14 3
knit - b13 3
miss - b12 3
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
xfer f17 bs17
rack -1
xfer bs13 f12
xfer bs14 f13
xfer bs15 f14
xfer bs16 f15
xfer bs17 f16
rack 0
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
tuck + f17 3
xfer b13 fs13
xfer b14 fs14
xfer b15 fs15
xfer b16 fs16
xfer b17 fs17
rack 1
xfer fs13 b12
xfer fs14 b13
xfer fs15 b14
xfer fs16 b15
xfer fs17 b16
rack 0
knit - b16 3
knit - b15 3
knit - b14 3
knit - b13 3
knit - b12 3
miss - b11 3
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
rack -1
xfer bs12 f11
xfer bs13 f12
xfer bs14 f13
xfer bs15 f14
xfer bs16 f15
rack 0
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
tuck + f16 3
xfer b12 fs12
xfer b13 fs13
xfer b14 fs14
xfer b15 fs15
xfer b16 fs16
rack 1
xfer fs12 b11
xfer fs13 b12
xfer fs14 b13
xfer fs15 b14
xfer fs16 b15
rack 0
knit - b15 3
knit - b14 3
knit - b13 3
knit - b12 3
knit - b11 3
miss - b10 3
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
rack -1
xfer bs11 f10
xfer bs12 f11
xfer bs13 f12
xfer bs14 f13
xfer bs15 f14
rack 0
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
tuck + f15 3
xfer b11 fs11
xfer b12 fs12
xfer b13 fs13
xfer b14 fs14
xfer b15 fs15
rack 1
xfer fs11 b10
xfer fs12 b11
xfer fs13 b12
xfer fs14 b13
xfer fs15 b14
rack 0
knit - b14 3
knit - b13 3
knit - b12 3
knit - b11 3
knit - b10 3
miss - b9 3
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
rack -1
xfer bs10 f9
xfer bs11 f10
xfer bs12 f11
xfer bs13 f12
xfer bs14 f13
rack 0
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
tuck + f14 3
xfer b10 fs10
xfer b11 fs11
xfer b12 fs12
xfer b13 fs13
xfer b14 fs14
rack 1
xfer fs10 b9
xfer fs11 b10
xfer fs12 b11
xfer fs13 b12
xfer fs14 b13
rack 0
knit - b13 3
knit - b12 3
knit - b11 3
knit - b10 3
knit - b9 3
miss - b8 3
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
rack -1
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
xfer bs12 f11
xfer bs13 f12
rack 0
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
tuck + f13 3
xfer b9 fs9
xfer b10 fs10
xfer b11 fs11
xfer b12 fs12
xfer b13 fs13
rack 1
xfer fs9 b8
xfer fs10 b9
xfer fs11 b10
xfer fs12 b11
xfer fs13 b12
rack 0
knit - b12 3
knit - b11 3
knit - b10 3
knit - b9 3
knit - b8 3
miss - b7 3
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
rack -1
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
xfer bs12 f11
rack 0
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
tuck + f12 3
xfer b8 fs8
xfer b9 fs9
xfer b10 fs10
xfer b11 fs11
xfer b12 fs12
rack 1
xfer fs8 b7
xfer fs9 b8
xfer fs10 b9
xfer fs11 b10
xfer fs12 b11
rack 0
knit - b11 3
knit - b10 3
knit - b9 3
knit - b8 3
knit - b7 3
miss - b6 3
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
rack -1
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
rack 0
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
tuck + f11 3
xfer b7 fs7
xfer b8 fs8
xfer b9 fs9
xfer b10 fs10
xfer b11 fs11
rack 1
xfer fs7 b6
xfer fs8 b7
xfer fs9 b8
xfer fs10 b9
xfer fs11 b10
rack 0
knit - b10 3
knit - b9 3
knit - b8 3
knit - b7 3
knit - b6 3
miss - b5 3
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
rack -1
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
rack 0
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
tuck + f10 3
xfer b6 fs6
xfer b7 fs7
xfer b8 fs8
xfer b9 fs9
xfer b10 fs10
rack 1
xfer fs6 b5
xfer fs7 b6
xfer fs8 b7
xfer fs9 b8
xfer fs10 b9
rack 0
knit - b9 3
knit - b8 3
knit - b7 3
knit - b6 3
knit - b5 3
miss - b4 3
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
rack -1
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
rack 0
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
tuck + f9 3
xfer b5 fs5
xfer b6 fs6
xfer b7 fs7
xfer b8 fs8
xfer b9 fs9
rack 1
xfer fs5 b4
xfer fs6 b5
xfer fs7 b6
xfer fs8 b7
xfer fs9 b8
rack 0
knit - b8 3
knit - b7 3
knit - b6 3
knit - b5 3
knit - b4 3
miss - b3 3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
rack -1
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
rack 0
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
tuck + f8 3
xfer b4 fs4
xfer b5 fs5
xfer b6 fs6
xfer b7 fs7
xfer b8 fs8
rack 1
xfer fs4 b3
xfer fs5 b4
xfer fs6 b5
xfer fs7 b6
xfer fs8 b7
rack 0
knit - b7 3
knit - b6 3
knit - b5 3
knit - b4 3
knit - b3 3
miss - b2 3
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
rack -1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
rack 0
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
tuck + f7 3
xfer b3 fs3
xfer b4 fs4
xfer b5 fs5
xfer b6 fs6
xfer b7 fs7
rack 1
xfer fs3 b2
xfer fs4 b3
xfer fs5 b4
xfer fs6 b5
xfer fs7 b6
rack 0
knit - b6 3
knit - b5 3
knit - b4 3
knit - b3 3
knit - b2 3
miss - b1 3
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
rack -1
xfer bs2 f1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
rack 0
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
tuck + f6 3
xfer b2 fs2
xfer b3 fs3
xfer b4 fs4
xfer b5 fs5
xfer b6 fs6
rack 1
xfer fs2 b1
xfer fs3 b2
xfer fs4 b3
xfer fs5 b4
xfer fs6 b5
rack 0
knit - b5 3
knit - b4 3
knit - b3 3
knit - b2 3
knit - b1 3
miss - b0 3
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
rack -1
xfer bs1 f0
xfer bs2 f1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
rack 0
knit + f0 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
tuck + f5 3
xfer b1 fs1
xfer b2 fs2
xfer b3 fs3
xfer b4 fs4
xfer b5 fs5
rack 1
xfer fs1 b0
xfer fs2 b1
xfer fs3 b2
xfer fs4 b3
xfer fs5 b4
rack 0
knit - b4 3
knit - b3 3
knit - b2 3
knit - b1 3
knit - b0 3
miss - b-1 3
xfer f0 bs0
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
rack -1
xfer bs0 f-1
xfer bs1 f0
xfer bs2 f1
xfer bs3 f2
xfer bs4 f3
rack 0
knit + f-1 3
knit + f0 3
knit + f1 3
knit + f2 3
knit + f3 3
tuck + f4 3
xfer b0 fs0
xfer b1 fs1
xfer b2 fs2
xfer b3 fs3
xfer b4 fs4
rack 1
xfer fs0 b-1
xfer fs1 b0
xfer fs2 b1
xfer fs3 b2
xfer fs4 b3
rack 0
knit - b3 3
knit - b2 3
knit - b1 3
knit - b0 3
knit - b-1 3
miss - b-2 3
xfer f-1 bs-1
xfer f0 bs0
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
rack -1
xfer bs-1 f-2
xfer bs0 f-1
xfer bs1 f0
xfer bs2 f1
xfer bs3 f2
rack 0
knit + f-2 3
knit + f-1 3
knit + f0 3
knit + f1 3
knit + f2 3
tuck + f3 3
xfer b-1 fs-1
xfer b0 fs0
xfer b1 fs1
xfer b2 fs2
xfer b3 fs3
rack 1
xfer fs-1 b-2
xfer fs0 b-1
xfer fs1 b0
xfer fs2 b1
xfer fs3 b2
rack 0
knit - b2 3
knit - b1 3
knit - b0 3
knit - b-1 3
knit - b-2 3
miss - b-3 3
xfer f-2 bs-2
xfer f-1 bs-1
xfer f0 bs0
xfer f1 bs1
xfer f2 bs2
rack -1
xfer bs-2 f-3
xfer bs-1 f-2
xfer bs0 f-1
xfer bs1 f0
xfer bs2 f1
rack 0
knit + f-3 3
knit + f-2 3
knit + f-1 3
knit + f0 3
knit + f1 3
tuck + f2 3
xfer b-2 fs-2
xfer b-1 fs-1
xfer b0 fs0
xfer b1 fs1
xfer b2 fs2
rack 1
xfer fs-2 b-3
xfer fs-1 b-2
xfer fs0 b-1
xfer fs1 b0
xfer fs2 b1
rack 0
knit - b1 3
knit - b0 3
knit - b-1 3
knit - b-2 3
knit - b-3 3
miss - b-4 3
xfer f-3 bs-3
xfer f-2 bs-2
xfer f-1 bs-1
xfer f0 bs0
xfer f1 bs1
rack -1
xfer bs-3 f-4
xfer bs-2 f-3
xfer bs-1 f-2
xfer bs0 f-1
xfer bs1 f0
rack 0
knit + f-4 3
knit + f-3 3
knit + f-2 3
knit + f-1 3
knit + f0 3
tuck + f1 3
xfer b-3 fs-3
xfer b-2 fs-2
xfer b-1 fs-1
xfer b0 fs0
xfer b1 fs1
rack 1
xfer fs-3 b-4
xfer fs-2 b-3
xfer fs-1 b-2
xfer fs0 b-1
xfer fs1 b0
rack 0
knit - b0 3
knit - b-1 3
knit - b-2 3
knit - b-3 3
knit - b-4 3
xfer b-4 f-4
knit + f-4 3
rack -1
xfer f-4 b-3
knit + b-3 3
rack 0
xfer b-3 f-3
knit + f-3 3
rack -1
xfer f-3 b-2
knit + b-2 3
rack 0
xfer b-2 f-2
knit + f-2 3
rack -1
xfer f-2 b-1
knit + b-1 3
rack 0
xfer b-1 f-1
knit + f-1 3
rack -1
xfer f-1 b0
knit + b0 3
rack 0
xfer b0 f0
knit + f0 3
rack -1
xfer f0 b1
knit + b1 3
rack 0
xfer b1 f1
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
x-stitch-number 106
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
outhook 3
drop f20
drop f19
drop f18
drop f17
drop f16
drop f15
drop f14
drop f13
drop f12
drop f11
drop f10
drop f9
drop f8
drop f7
drop f6
drop f5
drop f4
drop f3
drop f2
drop f1
